### ISSUE TITLE
FIDO U2F doesn't support WordPress Multisite

### ISSUE THREAD

**Issue by kasparsd** [georgestephanis/two-factor#102]
FIDO U2F maps website URI (App ID) with the Security key which makes it fail on WordPress Multisite where each site would need to re-register the key to make it work.

I'm not sure if there is any solution since WordPress doesn't support any kind of SSO solution by default.

**Comment by ethitter** [comment]
For networks up to a certain size, the "Multi-facet apps" approach from https://developers.yubico.com/U2F/App_ID.html could work. There's obviously a limit to how large that JSON can be, considering both generation time and the ability to cache it. Domain mapping also necessitates a filter on the list.

Over a certain size, if a network isn't handling login through a central URL, this will get interesting.

**Comment by teecee1** [comment]
Multisite admin are probably the most protective accounts. 
Should be made possible for U2F.
Al least with multisite using different domains (not subdomains).
At this time it is only working on one domain, where the U2F device is registered first. all other domains hang on login as if no U2F device present.

**Comment by dandrzejewski** [comment]
+1

**Comment by teecee1** [comment]
Any ideas? Any progress?
I think that the U2F key has to be registered and stored per domain and not only once per installation.
Could that be a solution?

**Comment by zaneselvans** [comment]
Also having this problem.  In the interim, is it possible to automatically detect the mismatch between the key and the domain, and fall back to another authentication method if there's one enabled?

**Comment by kasparsd** [comment]
Turns out [U2F doesn't allow facets that live on different domains](https://fidoalliance.org/specs/fido-u2f-v1.0-ps-20141009/fido-appid-and-facets-ps-20141009.html#h4_determining-if-a-caller-s-facetid-is-authorized-for-an-appid):

> All Web Origins listed must have host names under the scope of the same least-specific private label in the DNS, using the following algorithm:
>
> - The least-specific private label is the portion of the host portion of the AppID URL that matches a public suffix plus one additional label to the left.

So only `*.example.com` subdomains will be allowed where `.com` is the "public suffix" and `example` is the "one additional label to the left".

Essentially, faceted setup would work only for sub-domain multisites. The sub-directory multisite is already supported by the existing root level AppID.
