### ISSUE TITLE
Use JS to detect Fido U2F support

### ISSUE THREAD

**Issue by kasparsd** [georgestephanis/two-factor#117]
Quoting #116:

> After changing the http to https, and unconditionally returning true in providers/class.two-factor-fido-u2f.php, function is_browser_support, I can use the yubikey also with firefox and the u2f addon: https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/
> 
> So it would be nice if this would be supported from the plugin out of the box.

**Comment by Tea23** [comment]
It looks like this is happening because instead of checking for U2F support, the plugin just checks your user agent to see if it's Chrome 41+. I set a user agent override to `Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36` and it's working fine.

**Comment by Tea23** [comment]
Oh boy - really important caveat found... If I disable the override, the thing just *skips* U2F. This makes the U2F option in the plugin 100% redundant because an attacker can just set their user agent to Firefox, or actually use Firefox.

**Comment by kraftbj** [comment]
We'd probably need to figure out the best way to test for support. Is there a common standard we can check against instead of UA?

**Comment by norbusan** [comment]
Isn't there a way to check whether the actually used U2F function is available? Looking into the `Google/u2f-api.js` I see `u2f.getMessagePort` which tries to communicate. Isn't that the better test then checking for browser name?

**Comment by shield-9** [comment]
With current structure of this plugin, checking U2F availability using JavaScript isn't easy. (And AFAIK, there is no way to check server-side without using browser name and version.)

**Comment by norbusan** [comment]
Hmm, ok. Pity. What about simply doing *no* checks and metion in the docs that one needs to have either Chrome or Firefox with some plugin. Failures would be detected and indicated as such.

**Comment by Tea23** [comment]
I can use Github's U2F in Firefox with the plugin without changing my user agent. It could be worth investigating how they do the check.

**Comment by JacobHenner** [comment]
Any progress on this? Being able to use U2F with FF and WP would be great.

**Comment by shield-9** [comment]
Your pull request is welcome! (Including Firefox support) At the moment, I have no plan to work on this issue, because we need better way to detect browser support.

**Comment by kraftbj** [comment]
Thinking about how to do this, what do you think of:
1. Drop PHP browser check
2. Move check for `window.u2f` or something similar to detect for FIDO support via JS
3. If no JS support or if `window.u2f` fails, output message that their browser does not support their selected form of 2fa with a link to other methods and/or auto redirect to another method.
4. If `window.u2f` succeeds, loads the FIDO provider screen.

I haven't played with the code yet to see how horrible that would be to implement.

**Comment by JacobHenner** [comment]
How about an always-available button for U2F users, like the one provided by GitLab?

**Comment by pbudzon** [comment]
I can confirm the login works perfectly with Yubikey, Wordpress 4.6.1, Firefox 49.0.2 and 1.0 version of the u2f plugin when another plugin is used to change the user-agent to show the form.

**Comment by teecee1** [comment]
U2F Login works with Chrome and Firefox(incl Addon, no user-agent manipulation) in Nextcloud. 
Code is at https://github.com/nextcloud/twofactor_u2f

(Hope that helps; I can't contribute yet)

**Comment by grisu48** [comment]
Would appreciate it too, so the Two-Factor plugin with U2F would work with Firefox as well
