### ISSUE TITLE
Always use HTTPS for U2F AppId

### ISSUE THREAD

**Issue by Steltek** [georgestephanis/two-factor#118]
providers/class.two-factor-fido-u2f.php has this line:

`$app_url_parts = parse_url( home_url() );`

This makes the appId used for U2F dependent on whatever URL is configured as base URL in Wordpress. In my case, that is the http variant of my blog and as a result, the appId gets set to http://domain.tld, causing U2F to fail. It would be better to construct the appId based on the URL I am currently accessing, or at least convert the http from the Wordpress base URL to https (as U2F will never work on HTTP).

For example, changing this line:
                `$app_url = sprintf( '%s://%s', $app_url_parts['scheme'], $app_url_parts['host'] );`

to this:
                `$app_url = sprintf( 'https://%s', $app_url_parts['host'] );`

makes U2F work on my blog, regardless of whether the base URL points to http or https (as long as the login page and the likes are being accessed via https of course).

**Comment by timbru31** [comment]
Additionally if the home_url is configured via `wp-config.php` it was still `http`, so this does *not* work:

```php
define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST']);
define('WP_HOME', 'https://' . $_SERVER['HTTP_HOST']);
```

**Comment by kasparsd** [comment]
To be fixed with https://github.com/georgestephanis/two-factor/pull/125
