### ISSUE TITLE
Forcing two-factor login

### ISSUE THREAD

**Issue by szepeviktor** [georgestephanis/two-factor#120]
Would it be possible to force users to enable 2fa on the first login?

**Comment by szepeviktor** [comment]
off: I've came up with this very short MU plugin.
It will send an alternate registration email, and only allow TOTP login (username + TOTP).
https://github.com/szepeviktor/wordpress-plugin-construction/tree/master/mu-totp-login

**Comment by kasparsd** [comment]
Thanks for posting your solution @szepeviktor!
