### ISSUE TITLE
Allow Multisite admins to add U2F security tokens to other users

### ISSUE THREAD

**Issue by kasparsd** [georgestephanis/two-factor#127]
Should this be allowed @georgestephanis?

Currently it doesn't work because it references [the current user here](https://github.com/georgestephanis/two-factor/blob/b3e2eec7f4804ecc673e7ce9c644b9a6795c7158/providers/class.two-factor-fido-u2f-admin.php#L58).

**Comment by shield-9** [comment]
Duplicate of #88?

**Comment by kasparsd** [comment]
Indeed @shield-9 👍  I thought I had seen it somewhere :)
