### ISSUE TITLE
Update "tested up to" in README

### ISSUE THREAD

**Issue by pbudzon** [georgestephanis/two-factor#136]
Hi!

The plugin works perfectly fine with Wordpress 4.6.1, so the readme could be updated to reflect that :)

**Comment by nylen** [comment]
Works with 4.7 betas and trunk as well.

**Comment by kasparsd** [comment]
Great suggestion @pbudzon! Would you like to open a pull request?

**Comment by shield-9** [comment]
Fixed in #137
