### ISSUE TITLE
Update README.md with current integration plans for core

### ISSUE THREAD

**Issue by maplemuse** [georgestephanis/two-factor#140]
The readme still suggests that plans are in place to merge into core for 4.5 in February 2016. Since we're closer to Feb 2017, perhaps the Readme should be updated to reflect the current plans? 
(ie, discussions are still in place as to how to best integrate to core, timeline undetermined)?

**Comment by kraftbj** [comment]
Nod, needs to be updated.

**Comment by RiverRock** [comment]
+1

**Comment by kasparsd** [comment]
Fixed in #132.
