### ISSUE TITLE
Support U2F Zero

### ISSUE THREAD

**Issue by tarnover** [georgestephanis/two-factor#142]
Please add support for U2F Zero USB sticks. 

[https://github.com/conorpp/u2f-zero](https://github.com/conorpp/u2f-zero)

**Comment by kasparsd** [comment]
@tarnover Do you know what is required to support U2F Zero? It was my understanding that all U2F devices follow the same standard.

**Comment by shield-9** [comment]
It looks like "U2F Zero" is not certified by FIDO Alliance. (https://fidoalliance.org/certification/fido-certified/)
I think that we should test this plugin with FIDO-certified devices.

**Comment by kasparsd** [comment]
@shield-9 It should work as long as it follows the spec.

**Comment by tarnover** [comment]
When I try to add the U2F Zero from supported Chrome version that works with Google, Dropbox, and so on the button just goes directly to "Failed...". Even if I hit the button on the U2F Zero prior adding it. I do not see anything helpful in the logs to allude to why it failed. Thanks!

**Comment by kasparsd** [comment]
Thanks @tarnover! What does it say in the Chrome console?

**Comment by tarnover** [comment]
```
sign Object {version: "U2F_V2", challenge: "Ic6PTVGeTHhTOLtSEACQJstv1HAybO1v3cv2LI1kJVU", appId: "https://domain.com"}
u2f-api.js?ver=0.1.0-dev.1:678 Extension JS API Version:  1.1
fido-u2f-admin.js?ver=0.1.0-dev.1:27 Registration Failed 2
```
It seems to be looking for SSL so that might be the issue since this domain does not have it currently. Will add a LetsEncrypt cert to it and see if resolves the issue.

**Comment by kasparsd** [comment]
@tarnover Yes, U2F _requires_ TLS, from https://developers.yubico.com/U2F/App_ID.html

> Web facets must use HTTPS, and either use a Top-level domain or have localhost as hostname.

**Comment by tarnover** [comment]
That was it. Thanks for the help! Great plugin!

**Comment by kasparsd** [comment]
@tarnover Good to know. We should probably display a warning for sites without HTTPS.
