### ISSUE TITLE
problem adding new security key

### ISSUE THREAD

**Issue by bilalsalih** [georgestephanis/two-factor#143]
Hi,
I installed the plugin two-factor and it modifies user profile successfully. The issue is that when I try to add a new security key to a user it keep return "Failed" status. is this issue related that we do not use https for our login page? Would you help me with this issue? Thank you in advance. 

![16237668_1387797501294731_1454087337_n](https://cloud.githubusercontent.com/assets/25288855/22188331/2264993e-e0e2-11e6-91f8-fc8343ccfb43.jpg)

**Comment by maplemuse** [comment]
If you open the chrome developer console, there should be some kind of error message. 
Right click on an element in the page, select "Inspect" from the popup menu, and it should open the developer tools, and then select the console tab. 

There should be a line with the text "Registration Failed" and an error code. 

Does your security key support FIDO U2F? Some security keys may use an older type of security challenge which isn't supported.

**Comment by maplemuse** [comment]
But yes, this seems to be a duplicate of #79. FIDO U2F requires HTTPS.

**Comment by kasparsd** [comment]
Duplicate of #79.
