### ISSUE TITLE
Ensure that u2fL10n exists on wp-login.php before using it

### ISSUE THREAD

**Issue by pwallner** [georgestephanis/two-factor#153]
I saw an error on the "wp-login.php" page:

```
Uncaught ReferenceError: u2fL10n is not defined
at fido-u2f-login.js?ver=0.1.0-dev.1:3
at fido-u2f-login.js?ver=0.1.0-dev.1:15
```
It comes from file from file fido-u2f-login.js: Uncaught ReferenceError: u2fL10n is not defined:
```
window.console.log( 'sign', u2fL10n.request );
```

I can login, logout, everything, but it is an error...

**Comment by kasparsd** [comment]
Duplicate of #126.
