### ISSUE TITLE
Not receiving email for authentication code

### ISSUE THREAD

**Issue by natankawa** [georgestephanis/two-factor#154]
Hello,
I have set the authentication through email, but it turns out I am not receiving it when I try to login. 
Is there anything I can do to be able to deactivate the verification code requirement or any other solution to connect to my wordpress account?

**Comment by natankawa** [comment]
Finnally got to login with another account. I have checked my email, since I thought it might be incorrect and that could be the reason I wasn't receiving the code. The email was correct. Since I don't know what might be causing the error, I have deactivated the plugin for now.

**Comment by kasparsd** [comment]
Thanks for reporting the issue @natankawa!

You can disable the plugin by temporarily renaming the plugin folder `wp-content/plugins/two-factor` to something else over FTP, for example.
