### ISSUE TITLE
Invalidate email codes only when entered correctly

### ISSUE THREAD

**Issue by joshbetz** [georgestephanis/two-factor#155]
Email code are currently only invalidated if you type it in wrong. Instead, they should probably be invalidated after some time limit (maybe 60 seconds).

**Comment by kasparsd** [comment]
Indeed, it should also delete the token [if it was valid](https://github.com/georgestephanis/two-factor/blob/0c672510a9bdf608be93e7908779c3dc9ea59261/providers/class.two-factor-email.php#L77) to ensure that it can't be re-used.

**Comment by kasparsd** [comment]
@joshbetz The tokens should be invalidated the first time they're entered correctly to avoid re-using the same token. Most tokens are [one-time use to prevent replay attacks](https://en.wikipedia.org/wiki/One-time_password):

> This means that a potential intruder who manages to record an OTP that was already used to log in to a service or to conduct a transaction will not be able to abuse it, since it will no longer be valid

**Comment by joshbetz** [comment]
> The tokens should be invalidated the first time they're entered correctly to avoid re-using the same token.

Yep, #156 does that. This issue is about invalidating codes after some time limit though.

**Comment by kasparsd** [comment]
Thanks for the confirmation @joshbetz. What is the purpose of having the timeout now that the tokens are invalidated only after entered correctly (both #156 and #160)?

How about we add the "Email new access code" link instead?

**Comment by joshbetz** [comment]
#156 doesn't invalidate tokens after a timeout, only after they're entered correctly -- the same thing as #160. #155 is about the timeout.

**Comment by kasparsd** [comment]
@joshbetz I'm sorry for the confusion. I'm just trying to understand the use-case for having the timeout?
