### ISSUE TITLE
UX: Not easy to see that the TOTP method is configured

### ISSUE THREAD

**Issue by simonwheatley** [georgestephanis/two-factor#158]
It's not obvious that the “Time Based One-time Password” method is configured, once it has been configured:

<img width="534" alt="screen shot 2017-03-27 at 15 22 39" src="https://cloud.githubusercontent.com/assets/233434/24361217/451d0640-1301-11e7-8993-6f8a87ef0654.png">

There is a notice saying "enabled", but it's very small and only visible once you click on "View options":

<img width="557" alt="screen shot 2017-03-27 at 15 22 47" src="https://cloud.githubusercontent.com/assets/233434/24361235/52eeac4c-1301-11e7-8504-9533ac0fd164.png">

**Comment by georgestephanis** [comment]
We should add a visual indicator to all providers -- maybe a green border on the left side or something or a checkmark afterwards -- indicating that it's not only enabled but configured.

This really needs some UX design attention.

**Comment by joshbetz** [comment]
I think the checkbox in the "Enabled" column is relatively obvious, though I'm not opposed to a better UI. Maybe we could get rid of the View Options dropdown when it has been configured for now since it doesn't do anything anyway?

**Comment by kasparsd** [comment]
Fixed in #169.
