### ISSUE TITLE
New U2F code problems

### ISSUE THREAD

**Issue by norbusan** [georgestephanis/two-factor#163]
Hi,
thanks for doing the work in https://github.com/georgestephanis/two-factor/pull/162 I have tried the new plugin structure and can confirm that as is I could log out and log back in using my Yubikey Neo on FIrefox with the U2F plugin, no patching necessary anymore. Big thanks!

A few small glitches I would like to report:

- Next to the "Register key" there is still written "FIDO U2F is not supported in your web browser. Try using Google Chrome.", one might change this message.
- pressing "Register key" with my Yubikey plugged in I get "U2F device ineligible." but fortunately my previously registered device is still here (maybe the ineligible comes from registering the same device twice?)

Anyway, thanks a lot again

Norbert

**Comment by georgestephanis** [comment]
Will try to investigate shortly.

Any chance you can try a git bisect to see if you can track down where it broke?

**Comment by kasparsd** [comment]
> Next to the "Register key" there is still written "FIDO U2F is not supported in your web browser. Try using Google Chrome.", one might change this message.

@norbusan That's because the Google U2F JS library we're using doesn't report a valid JS API version on Firefox. The warning can be ignored.

> pressing "Register key" with my Yubikey plugged in I get "U2F device ineligible."

Unfortunately the Google U2F JS library doesn't provide a lot of information in their error responses. I think you're right about the key being already registered with the site.

Can you please try removing and re-adding your key?

**Comment by georgestephanis** [comment]
Was it a new key you wanted to register?  Or re-register an existing one?

**Comment by norbusan** [comment]
Ok, I tried it and it was as I fathomed: Removing the already registered Yubikey I was able to re-register it without errors.

So yes, besides the fact that some error messages are a bit misleading, all is fine.

Big thanks!

**Comment by kasparsd** [comment]
Thanks for the confirmation @norbusan!

I'm closing this and created #165 just for the failed Firefox U2F support detection.
