### ISSUE TITLE
Please Integrate with Theme My Login

### ISSUE THREAD

**Issue by iAmSaugata** [georgestephanis/two-factor#164]
Hi,
Could you please integrate this with Theme My Login, it will be much better in terms of unifying user logon screen.

Regards,
Saugata D.

**Comment by kasparsd** [comment]
Thanks for the suggestion @iAmSaugata!

Maybe the developers of Theme My Login can look into what is required to get this done? We're happy to add any hooks and filters as long as they help other plugins.
