### ISSUE TITLE
Create a changelog for the wordpress repository

### ISSUE THREAD

**Issue by pjv** [georgestephanis/two-factor#170]
Anyone using this plugin has to find their way here and look at the list of commits in order to see what changes are included in a given update. Would it be too much trouble to create a changelog in the plugin and update it when you push a release to the WP repo so that users could see what has changed from their admin dashboard without having to go looking for the commits page here?

Failing that, do you think you could put the URL to the commits page of this github repo into the description for the plugin so at least it's a simple click to find what has changed before you update?

Failing that, maybe you should remove the plugin from the WP repository until you deem it ready enough for use that you can do a full public release. Beta testers can just get the zip from here.

**Comment by voldemortensen** [comment]
Hello @pjv,

We appreciate your concern for users, and frankly, I think its a great idea to be including a change log and would like to see that implemented. It would be far easier to include a link to the commits page, and maybe that could be done in the interim of getting a change log put together. On the point of removing this plugin from wordpress.org, that is unlikely to happen. It is currently listed as a beta plugin, not as a regular plugin: https://wordpress.org/plugins/browse/beta/
Keeping the plugin on wordpress.org helps with discovery, updates, and feedback from users.

Thanks again!

**Comment by kasparsd** [comment]
@pjv This plugin is automatically versioned and pulled in by a script on WP.org:

https://meta.svn.wordpress.org/sites/trunk/api.wordpress.org/public_html/dotorg/github-sync/

and there is a bug where it creates a new version every time somebody opens a pull request. #171 will probably create another release :) And it did:

<img width="334" alt="two-factor-version" src="https://cloud.githubusercontent.com/assets/169055/24557801/bfe20c66-1641-11e7-891c-e32dfb45f941.png">

This prevents us from proper versioning and releases.

**Comment by pjv** [comment]
That's a retarded script, then. Can I suggest un-hooking that? 

I use [Mike Jolley's script](https://github.com/mikejolley/github-to-wordpress-deploy-script) for my own plugins which does the same thing but you manually kick it off when an update is appropriate.

**Comment by kasparsd** [comment]
Fixed in #171.
