### ISSUE TITLE
Unable to register Security Key

### ISSUE THREAD

**Issue by arjanvandenbos** [georgestephanis/two-factor#173]
Unable to register Security Key > U2F request timeout reached.

**Comment by kasparsd** [comment]
@arjanvandenbos Are you seeing any error messages in the browser console? Secondly, are you viewing the page over HTTPS? Finally, which browser are you using?

**Comment by kasparsd** [comment]
Closing since we can't replicate it.

**Comment by arjanvandenbos** [comment]
Sorry for not responding earlier.
Page is viewed over HTTPS
Using Chrome, latest stable version 57

When I click on 'Register new key', you just see the spinner
After a while (a minute), I get the notification 'U2F request timeout reached' (to the right of the 'Register new key' button (see screenshot 
![22ab](https://cloud.githubusercontent.com/assets/14236904/24817914/54c333b6-1bd6-11e7-874f-935f57cd33f6.png)

I had installed Two-factor successfully on a number of sites. 
This was another site I wanted to use my Yubikey on,  with above results.
I tried again with all other plugins deactivated > same result

I then went to a site where Two-factor was already installed, with a security key registered. I deleted the key and tried to register a new one, I got the same result as on the first site ( 'U2F request timeout reached'). So it did work fine before. 

Both sites are hosted with the same host (Siteground) but on different shared accounts.

What kind of details do you need from me for further investigation?
