### ISSUE TITLE
Reopening 3173 Unable to register Security Key

### ISSUE THREAD

**Issue by arjanvandenbos** [georgestephanis/two-factor#174]
Sorry for not responding earlier on #173

- Page is viewed over HTTPS
- Using Chrome, latest stable version 57

When I click on 'Register new key', you just see the spinner
After a while (a minute), I get the notification 'U2F request timeout reached' (to the right of the 'Register new key' button (see screenshot
![22ab](https://cloud.githubusercontent.com/assets/14236904/24836041/7e261c08-1d09-11e7-802b-d80ca76eaba9.png)

I had installed Two-factor successfully on a number of sites.
This was another site I wanted to use my Yubikey on, with above results.
I tried again with all other plugins deactivated > same result

I then went to a site where Two-factor was already installed, with a security key registered. I deleted the key and tried to register a new one, I got the same result as on the first site ( 'U2F request timeout reached'). So it did work fine before.

Both sites are hosted with the same host (Siteground) but on different shared accounts.

What kind of details do you need from me for further investigation?

**Comment by kasparsd** [comment]
@arjanvandenbos Can you please check the browser console for any error messages? What kind of U2F key do you have? Secondly, have you tried adding the key on a different computer?

**Comment by arjanvandenbos** [comment]
The issue is resolved; not sure what happened, most likely user error
I am using a Yubikey
Ticket can be closed
