### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by simplenotezy** [georgestephanis/two-factor#184]
After having installed two-factor following happens:

1. Asks me to login using WordPress.com
2. After being redirected from WordPress, it asks for a Authentication Code. I enter the one for my blog.
3. I get error "There was an error logging you in via WordPress.com, please try again or try logging in with your username and password."
4. I try to login manually, using my local WordPress account.
5. I am redirected to the following screen:
![image](https://user-images.githubusercontent.com/3786627/27185647-5009cd58-51e6-11e7-9cca-15c6b88cad69.png)

**Comment by kasparsd** [comment]
Thanks for reporting the issue @simplenotezy! Do you have Jetpack enabled -- there is #122? The Two-Factor plugin doesn't include any WordPress.com integration.

**Comment by djibux** [comment]
@simplenotezy, you can use the following workaround.  Once on the screen referenced in step 5, click on the bottom link to switch to "Backup Verification Codes" then switch back to "One-time passwords".

**Comment by kasparsd** [comment]
Fixed in #196.
