### ISSUE TITLE
WP 4.8 No email with code

### ISSUE THREAD

**Issue by pwallner** [georgestephanis/two-factor#187]
Today I updated to WP 4.8, during login when I use send email code, no email is arriving... U2F is working...

**Comment by nickmomrik** [comment]
Ran into this today as well. Seems related to #177. I was able to go into the usermeta table and delete everything with the meta_value = '_two_factor_email_token' to get users working again.

**Comment by kasparsd** [comment]
Indeed, this is a duplicate of #177.
