### ISSUE TITLE
Possibility to remove Google Authenticator

### ISSUE THREAD

**Issue by pwallner** [georgestephanis/two-factor#188]
Can you add the possibility to remove the stored Google Authenticator. I can only see "activated" but I cannot remove it anymore...

**Comment by My1** [comment]
wouldnt disable do the trick normally? didnt try though.

**Comment by kasparsd** [comment]
This was fixed in #252.

**Comment by My1** [comment]
oh intresting. so deactivating TOTP didn't grill the key? nice to know.

@kasparsd thx for fixing this.

**Comment by kasparsd** [comment]
@My1 Yeah. Probably didn't want users to have to re-scan the code every time they disabled the method.

**Comment by My1** [comment]
makes sense, I totally didnt think of that. I personally invalidate old credentials when turning off something so someone won't accidentially end up getting into lockouts (e.g. the code should NEVER be shown to the user ever again after the first time, add a reset 2FA device and you have it) or potential holes (e.g. someone else obtained access to the 2FA method and the user disables and re-enables in the hope of reset and locking the attacker out.)
