### ISSUE TITLE
Wordpress mobile app integration

### ISSUE THREAD

**Issue by nthdegreeburns** [georgestephanis/two-factor#190]
The plugin works well out of the box. I did try and use it with the official Wordpress mobile app (iOS), and the TFA dialogue wasn't presented to me until after I logged in and tried to preview a post. Then the TFA dialogue from your plugin appeared and basically blocked the preview action. I couldn't get the TFA code to work.

**Comment by kasparsd** [comment]
@nthdegreeburns Thanks for reporting the issue! Could this be a duplicate of #122?

**Comment by nthdegreeburns** [comment]
It sounds vaguely similar, yes. I would suspect this would be a closed issue if the bug fix was in 2 days ago and then wait for it to come back up again. I'm not using the mobile app for another reason right now -- it just is very limited in its capabilities.

**Comment by kasparsd** [comment]
Thanks @nthdegreeburns! I'll close this out for now. Feel free to re-open if this pops up again.
