### ISSUE TITLE
U2F device ineligible with Yubikey (Blue)

### ISSUE THREAD

**Issue by GeoSn0w** [georgestephanis/two-factor#191]
I can't seem to get the Yubikey (blue) to be registered.
When I connect the device and tap the golden circle, on "Security Keys" it returns: U2F device ineligible.
I do use SSL.

**Comment by kasparsd** [comment]
Thanks for reporting the issue @GeoSn0w!

Does the same key work on Google or GitHub, for example?

That error code is coming from [the U2F API](https://github.com/georgestephanis/two-factor/blob/c220afbc9464f07abef6dd961da7d09857544272/includes/Google/u2f-api.js#L70).

Do you see any additional information in the browser console?

**Comment by GeoSn0w** [comment]
Yes, the key works fine on GitHub, Facebook, Gmail, etc. but it is the blue one that can't be programed with the Personalization Tool from YubiKey (if that helps in any way).

**Comment by GeoSn0w** [comment]
We can mark this as solved, reinstalling the plugin 2 times solved the issue (for some reason). I was able to add the key.

**Comment by kasparsd** [comment]
Thanks for sharing that link @My1! Could you please open an issue for this? It would be great to have more helpful error messages.
