### ISSUE TITLE
One Time Password doesn’t work with a ? in site title via QR

### ISSUE THREAD

**Issue by KittMedia** [georgestephanis/two-factor#192]
If I add a `?` in my site title the QR code is getting invalid. Thus I can’t enable the One Time Password. As soon as I removed the `?` from the site title it’s working.

**Comment by kasparsd** [comment]
Thanks for reporting the issue @KittMedia! I could replicate it:

![invalid](https://user-images.githubusercontent.com/169055/30780279-fed6df74-a10f-11e7-908c-550068a98672.jpg)

It appears to be URL encoded properly during [`get_google_qr_code()`](https://github.com/georgestephanis/two-factor/blob/8fb4a34595ae6568f87386284585c206c5601534/providers/class.two-factor-totp.php#L295-L303) so it might be the Authenticator app failing at decoding.

The `provider` parameter supports any string as long as it is encoded:
https://github.com/google/google-authenticator/wiki/Key-Uri-Format

Here is a sample QR code that will fail:
https://chart.googleapis.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth%3A%2F%2Ftotp%2Fexample.com%3Fsecret%3D123%26issuer%3Dexample%3Fquestionmark

**Comment by kasparsd** [comment]
@KittMedia This should be fixed now.
