### ISSUE TITLE
Email authentication not working with SMTP

### ISSUE THREAD

**Issue by richb8** [georgestephanis/two-factor#198]
Hi,

I have an SMTP plugin 'WP Mail SMTP by WPForms' which overrides the wp_mail() function to use SMTP. However, the Two Step email authentication is not sending the codes using these smtp details.

Any ideas?

**Comment by kasparsd** [comment]
@richb8 No idea. We're using the standard `wp_mail()` calls everywhere.

Could this be related to #177 instead? Try deleting the `_two_factor_email_token` user meta entry.

**Comment by richb8** [comment]
Looks like it, cheers!

**Comment by Ardakilic** [comment]
I had the exact same issue, removing `_two_factor_email_token` solved on my case, too! Thanks!

**Comment by kasparsd** [comment]
@Ardakilic The latest version has a "Resend Code" button for this purpose when you log in.

**Comment by Ardakilic** [comment]
@kasparsd Thanks! Actually I'd update if I could log in, so I was kinda stuck there 😄

**Comment by kasparsd** [comment]
@Ardakilic Oh, right... didn't think about that!

**Comment by Ardakilic** [comment]
@kasparsd no worries! The ntp sync on my server was disabled for a reason and totp was not working, so yesterday night I had myself panicked for a whole 5 miutes :)
