### ISSUE TITLE
Allow other plugins to bypass two-factor authentication

### ISSUE THREAD

**Issue by cheelahim** [georgestephanis/two-factor#199]
Hey guys. We're working on WP plugin for Civic Identity Platform authentication. The authentication flow is somewhat similar but does not require a second factor to authenticate user. There is a conflicting workflow issue when both our plugins installed and enabled. Check blockvis/civic-sip-wp#4 for details.

The issue is that Civic authentication flow is interrupted by two-factor plugin but it is not necessarily required by business logic. A user should have a choice to login with Civic or go with standard WP login and to be asked for second factor as per your plugin intended workflow.

The reason for this conflict is that two-factor plugin hooks to `wp_login` action to interrupt the authentication flow. Our plugin also dispatches `wp_login` action to provide backward compatibility and stick with WP authentication protocol.

We need to find a solution for out plugins to co-exist.
Whether you think it is possible for you to an add extra argument to `Two_Factor_Core::wp_login` which would allow to bypass the 2FA regardless of the user settings?
Something like this:

```php
	public static function wp_login( $user_login, $user, $bypass = false) {
		if ( $bypass || ! self::is_user_using_two_factor( $user->ID ) ) {
			return;
		}

		wp_clear_auth_cookie();

		self::show_two_factor_login( $user );
		exit;
	}
```
May be you have a better idea how to make your plugin co-exist with other authentication solutions.

**Comment by kasparsd** [comment]
@cheelahim Another solution is for you to unhook the two-factor `wp_login` task whenever necessary:

```
remove_action( 'wp_login', array( 'Two_Factor_Core', 'wp_login' ), 10, 2 );
```
