### ISSUE TITLE
This is not working on a WP Engine site

### ISSUE THREAD

**Issue by pelicanpaul** [georgestephanis/two-factor#201]
When I try to authenticate with the code form email I get  502 Bad Gateway
nginx

Ideas?

**Comment by gilmourcraves** [comment]
Interesting. Coming back to this. Now it does not send the email. I have checked to see if emails are sent and they do send but with this plugin they are not sent. - Paul

**Comment by kasparsd** [comment]
@pelicanpaul Do you have access to the PHP or Nginx error logs? It is almost impossible to debug this without specific details on where it fails.

**Comment by pelicanpaul** [comment]
Yep. I looked at the errors but there is nothing there related to this.  But the mail settings are as follows.

SendMail path (UNIX): /usr/sbin/sendmail -t -i
SMTP server (Windows): localhost
SMTP port (Windows): 25
Add X header: 1

**Comment by pelicanpaul** [comment]
On another WP engine site I see the 

502 Bad Gateway
nginx

Error with /wp-login.php?action=validate_2fa
page

**Comment by pelicanpaul** [comment]
It was discovered that the email is sent from an account that was created AFTER the plugin is installed. Not sure why???

**Comment by kasparsd** [comment]
@pelicanpaul Could you please ask WP Engine support for the related errors logs? We really need to know which part of the code is triggering the error. Thanks!

**Comment by kasparsd** [comment]
Closing for now. Please re-open if more details can be provided.

**Comment by pelicanpaul** [comment]
Hi, Finally got this working with support from WP Engine. The tech guys said "I had to disable one of our login protection settings conflicting with it."  Not sure what it was but what a freakin pain in the ass not having access to the server settings and misc security stuff.

**Comment by ccoley** [comment]
I encountered this issue as well and it was because WP-Engine uses a filter to add a `wpe-login=true` parameter to the login form's action URL. It does this with a filter on the `site_url` hook that only applies when the scheme is `login_post`. I've submitted a pull request that applies this filter when running in WP-Engine environments.

#257
