### ISSUE TITLE
Please add Russian translation made in WordPress translаtor

### ISSUE THREAD

**Issue by DeeKey** [georgestephanis/two-factor#202]
https://translate.wordpress.org/locale/ru/default/wp-plugins/two-factor

**Comment by kasparsd** [comment]
Thanks @DeeKey!

I believe the translations are handled automatically by the WP.org servers, see https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/

**Comment by DeeKey** [comment]
@kasparsd 
You had to accept suggested translations to include them to WordPress distribution system.
Currently Russian translations are in suggested state. 
Please accept them!

**Comment by DeeKey** [comment]
You can check translations by sorting Waiting column here:
https://translate.wordpress.org/projects/wp-plugins/two-factor

**Comment by kasparsd** [comment]
@DeeKey Unfortunately I don't have access to do that:

![translation-accept-access](https://user-images.githubusercontent.com/169055/33676151-8e9e1c94-dabd-11e7-9a20-bdac3eda1a33.png)

I can't even do it for my own plugins. Not sure why.

**Comment by kasparsd** [comment]
Here is the logged-in screenshot:

![translation-accept-access](https://user-images.githubusercontent.com/169055/33676190-b1daa06a-dabd-11e7-8ac8-881eafcdadf3.png)

**Comment by DeeKey** [comment]
You need to ask or permission in slack channel
Here is more informaion about this:
https://make.wordpress.org/plugins/tag/language-packs/

**Comment by DeeKey** [comment]
@kasparsd could you please add me as a Russian translator to your plugin?
Here is the procedure to make it:
https://make.wordpress.org/polyglots/handbook/rosetta/theme-plugin-directories/

**Comment by DeeKey** [comment]
@kasparsd Try this way:
1) Login to Wordpress.org
2) Go to Russian Translation section
3) There is a drop down list in the bottom left corner near "Legend:" text for Bulk actions.
4) Choose Approve.

Hope it helps!

**Comment by kasparsd** [comment]
@DeeKey I don't seem to have the necessary permissions to do that -- here is the error message:

![not-allowed](https://user-images.githubusercontent.com/169055/34108217-eaf9d796-e407-11e7-97bf-5adc7f74bf49.png)

**Comment by DeeKey** [comment]
@kasparsd  Seems, that I figured it out!

Post as a New Post here:
https://make.wordpress.org/polyglots/
the following text:

    Hello Polyglots, I am the plugin author for [plugin-name and link to plugin directory]. We have a number of great translation editors that we’d like to be able to approve translation for our plugin(s). Please add the following WordPress.org users as translation editors for their respective locales:

        #ru_RU – @VaultDweller
        etc…

    If you have any questions, just comment here. Thank you!
#editor-requests
