### ISSUE TITLE
Kill session? I dont understand - Possible (BUG)

### ISSUE THREAD

**Issue by Milor123** [georgestephanis/two-factor#206]
**I've disable all my plugins and also I've tested it in chrome and firefox quantum.**

I use **TOTP** for two factor with your plugin

1. go to /wp-admin and auth with my admin user, It create **2 sessions.**
2. then when I close the firefox or chrome
3. now try open my /wp-admin (it should go to dashboard) NOPE, it asks me to login again. then i must open a new session

At first I thought it was a mistake of my chrome, but when I disable your plugin, and close my browser, and retry to login, the session is remembered as it should be!

**Observations**: When I search for the old sessions are not destroyed
**Note**: It begins to happen a few weeks ago

**Comment by kasparsd** [comment]
> It create 2 sessions.

Could you please elaborate on that? Where and how do you see them as two sessions?

I couldn't replicate the issue on my blog, for example.

**Comment by Milor123** [comment]
@kasparsd  You have reason, its my mistake, the plugin Latch is killing (or is omitting somthing that need the browser for keep session). Sorry, close this thread. thanks!
