### ISSUE TITLE
u2f support in Firefox

### ISSUE THREAD

**Issue by voldemortensen** [georgestephanis/two-factor#211]
Firefox 57 included the option to turn on u2f support. It would be nice to update our detection to allow Firefox users to use u2f.

**Comment by voldemortensen** [comment]
A few more details, I was able to register a key and activate u2f from Firefox, however logging in does not detect the key.

**Comment by kasparsd** [comment]
Thanks for reporting the issue @voldemortensen! Could you please paste the browser console output when you login?

**Comment by voldemortensen** [comment]
Yep, doing some digging and then I'll provide what I can. It doesn't help that Firefox keeps crashing :(

**Comment by voldemortensen** [comment]
Alright, here's the error `TypeError: setting getter-only property "u2f"` that comes from this line: https://github.com/georgestephanis/two-factor/blob/master/includes/Google/u2f-api.js#L17

The issue is that the Google u2f library does funky things. Two other projects I was able to find have/had the same issues.
https://github.com/kvhnuke/etherwallet/issues/1122
https://github.com/nextcloud/twofactor_u2f/pull/74

**Comment by tayvano** [comment]
Supposedly https://www.npmjs.com/package/u2f-api fixes it. We haven't had the chance to fully debug and test across all browsers yet tho and haven't made the change yet

**Comment by voldemortensen** [comment]
Thanks for the input @tayvano, definitely appreciated. I've done minimal testing but haven't been able to get anything to work yet. I'm still lost as to why I can register a key just fine, but can't login with it.

**Comment by gstammw** [comment]
As with Firefox 60 there are no problems anymore and U2F works like a charm.
Please remove the "your browser is not supported" message for Firefox >= 60.

**Comment by kasparsd** [comment]
I've confirmed the U2F to be working correctly with Yubikey NEO and Firefox 61.0 (64-bit) on MacOS 10.13.5 as long as the [feature flag](https://www.yubico.com/2017/11/how-to-navigate-fido-u2f-in-firefox-quantum/) is enabled.

**Comment by onliniak** [comment]
Yubikey 4 | Firefox 65 | Arch Linux 4.20.2 | here and works. 

PS: Try hold for about 3 seconds, not just tap. Yubikey Personalization detect key ?

**Comment by kasparsd** [comment]
Re-opening since U2F is no longer working with Firefox 67.0.

**Comment by kasparsd** [comment]
I've opened #283 to address the `TypeError: setting getter-only property "u2f"` issue.

#284 fixes the issue with Firefox being reported as unsupported "FIDO U2F is not supported in your web browser. Try using Google Chrome.".
