### ISSUE TITLE
I would like to use this as a mu-plugin

### ISSUE THREAD

**Issue by snellcode** [georgestephanis/two-factor#214]
It seems to work as a mu-plugin. Just want to ask if you think there would be any problem with this? Are the any path references, etc.. that I should be concerned about since it's not in the expected place? It just makes this easier for us to deploy if we can have it in mu-plugins. Thanks, great job!

**Comment by kasparsd** [comment]
@snellcode It should work just fine however we're not running any tests in a mu-plugin environment so I can't tell for sure. Please post your findings here if something doesn't work.
