### ISSUE TITLE
Display on a custom page instead of wp-login.php

### ISSUE THREAD

**Issue by sanludhi** [georgestephanis/two-factor#222]
Hi, 

It's a great plugin. Very good job done. 

Was wondering if forms can be displayed on a custom page instead of wp-login.php, as i have custom user- login, registration ... and also in other custom forms if required.

Thanks

**Comment by pgreivel** [comment]
I was wondering the same and look forward to be able to achive that and use my custom page too! :)

**Comment by kasparsd** [comment]
@sanludhi Currently a lot of the [logic relies on the core WP login page hooks](https://github.com/georgestephanis/two-factor/blob/master/class.two-factor-core.php#L330) so it isn't possible to use the second factor inputs outside the default WP login area.

**Comment by kasparsd** [comment]
Leaving open as a feature request.

**Comment by nielspeen** [comment]
Adding a _do_action_ to my existing login logic was sufficient to trigger the two-factor dialog in my case:

`...
do_action( 'wp_login', $user->user_login, $user );
return $user;`

Only thing missing is a filter that allows me to modify two-factor's HTML output.

**Comment by kasparsd** [comment]
Thanks for the confirmation @nielspeen!

So it appears that the two factor authentication can be added to any login form as long as the login request is sent to `wp-login.php` or any other controller that triggers the `wp_login` hook.

We need to document the `redirect_url` input field which can be used to redirect users to any custom URL after the second factor authentication. I've created #278 for that.

**Comment by pgnd** [comment]
@kasparsd @nielspeen 

did this get ironed out?

After adding simple login redir with
```
function redir_login(){
	global $pagenow;
	$redirPage = 'https://example.com/my-login';
	if(
		'wp-login.php'  == $pagenow  &&
		$_GET['action']!= "logout"   &&
		$_GET['action']!= "lostpassword"
	) {
		wp_redirect($redirPage);
		exit();
	}
}
add_action('init','redir_login');
```

, where RegistrationMagic provides the login page logic, when enabled two-factor DOES intercept, but on token submit, simply does ... nothing (as far as I've been able to figure out so far).

Login/logout/registration work fine otherwise .

Is there a two-factor fix for that^?  Or have I missed some config ... ?
