### ISSUE TITLE
Call_Useer_Func_Array() Error.

### ISSUE THREAD

**Issue by JonnyPetts** [georgestephanis/two-factor#223]
Hello, 
I seem to be getting this error when on the Authorisation page when logging in  - 
`Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wp_login_viewport_meta' not found or invalid function name in /home/(databasename)/public_html/wpi-includes/clsss-wp-hook.php on line 286`

I have narrowed it down to this plugin as I have no issues signing on when the plugin is disabled. 

Any help with what this could be / a fix ?

**Comment by kasparsd** [comment]
`wp_login_viewport_meta()` seems to be [a valid function](https://developer.wordpress.org/reference/functions/wp_login_viewport_meta/) provided by WP core. Which version of WP are you running? What other plugins do you have installed?
