### ISSUE TITLE
vveighvltlflehhenefnkvldrelhrrbchjfkevedciik

### ISSUE THREAD

**Issue by luc-lynx** [georgestephanis/two-factor#236]

**Comment by luc-lynx** [comment]
mistakenly pushed button on my yubikey. I'm sorry, please delete the issue

**Comment by kasparsd** [comment]
@luc-lynx Unfortunately, it appears that GitHub [doesn't support deleting issues](https://stackoverflow.com/questions/3081521/how-to-completely-remove-an-issue-from-github).
