### ISSUE TITLE
Deployments to WP.org

### ISSUE THREAD

**Issue by kasparsd** [georgestephanis/two-factor#251]
Looks like none of the recent pull requests have been deployed to WP.org:

https://plugins.svn.wordpress.org/two-factor/trunk/

and the SVN directories are all empty :(

**Comment by kasparsd** [comment]
@dd32 Could you please help debug this?

Why is the [WP.org SVN repository for this plugin](https://plugins.svn.wordpress.org/two-factor/trunk/) empty?

[Here are the most recent merges](https://github.com/georgestephanis/two-factor/commits/master) that should have reached WP.org.

Thank you!

**Comment by kasparsd** [comment]
Here is the [SVN commit that deleted everything](https://plugins.trac.wordpress.org/changeset?sfp_email=&sfph_mail=&reponame=&new=1895246%40two-factor%2Ftrunk&old=1240091%40two-factor%2Ftrunk).

**Comment by dd32** [comment]
@georgestephanis Can you check the webhook logs and send me the latest output from it on slack?

I've resync'd the plugin for now: https://plugins.trac.wordpress.org/changeset/1945808

**Comment by georgestephanis** [comment]
I sent the deets to Dion in Slack, but it looks from the response like the server running the `/github-sync/feature-plugins.php` doesn't have git installed? o.0

The script output/response looks like this:

```
Merging from git://github.com/georgestephanis/two-factor.git to https://plugins.svn.wordpress.org/two-factor/trunk/
/home/api/public_html/dotorg/github-sync/feature-plugins.sh: line 56: git: command not found
/home/api/public_html/dotorg/github-sync/feature-plugins.sh: line 59: git: command not found
/home/api/public_html/dotorg/github-sync/feature-plugins.sh: line 67: git: command not found




Synced from git://github.com/georgestephanis/two-factor.git
mv: cannot stat '/tmp/gh-plugin-sync-Zn7fgFY/_temp-github/*': No such file or directory
No changes found in the SVN repository.
Sync Done.
```

**Comment by dd32** [comment]
Thanks george! It's probably a path issue, but I'll have a look into it in a few days (jumping on a plane momentarily)

**Comment by kasparsd** [comment]
I'll stop pushing and merging code for now -- it got deleted again https://plugins.trac.wordpress.org/changeset/1948750

**Comment by kasparsd** [comment]
@dd32 Did you manage to look into this? I would like to merge in #248 as a fix for #253.

**Comment by kasparsd** [comment]
@georgestephanis Do you have any new information on this? Would like to get #248 merged in.

**Comment by dd32** [comment]
Just keep merging things. It'll be fixed when it's fixed.

**Comment by kasparsd** [comment]
@dd32 Could you please disable the automatic deployments on WP.org now that we have the build and deploy tools added to the repository? Thanks!

**Comment by dd32** [comment]
Sure, feel free to remove the Github webhooks which trigger it.

**Comment by kasparsd** [comment]
Oh, right. Totally didn't think of that.

@georgestephanis Could you please help with this since I don't have access to repo config?

**Comment by kasparsd** [comment]
This is now done. Deployments are now manual and require running `npm run deploy`.
