### ISSUE TITLE
Remove non-error console.log

### ISSUE THREAD

**Issue by kkmuffme** [georgestephanis/two-factor#262]
Could you please remove the console.log that are just informative and not a real error.

It's really not necessary (which is why no other plugins do it upon release) & when logging js console messages (as most production environments do), it's just a pita and I don't really want to add it to the js excludes list, when the source can be adjusted.

Thanks :-)

**Comment by kasparsd** [comment]
Thanks for the suggestion @kkmuffme! Totally agree.

Could you please open a pull request with the suggested changes?

**Comment by kkmuffme** [comment]
Done, see https://github.com/georgestephanis/two-factor/pull/264
