### ISSUE TITLE
2FA can easily be circumvented/not working for WooCommerce

### ISSUE THREAD

**Issue by kkmuffme** [georgestephanis/two-factor#263]
When using WooCommerce & logging in via the My Account page (or in fact: any custom login form) it won't ask for the Two Factor code.

**Comment by kasparsd** [comment]
Probably related to #258. I specifically tested the change with WooCommerce and the checkout page and it did redirect user login to the Two Factor page.

Which shortcode are you using on the My Account page?

**Comment by kasparsd** [comment]
@kkmuffme Ping.

**Comment by Camilo517** [comment]
But what is the shortocode to show it? @kasparsd

**Comment by kasparsd** [comment]
@Camilo517 I was referring to WooCommerce shortcodes that include the login form as part of the output. For example, I tested #258 with `[woocommerce_checkout]` and it redirected to the 2FA form as expected.

**Comment by kasparsd** [comment]
@Camilo517 The front-end "user settings" for 2FA is covered by issues #189 and #247 while this one was about 2FA when using the existing WooCommerce shortcodes:

> When using WooCommerce & logging in via the My Account page (or in fact: any custom login form) it won't ask for the Two Factor code.

**Comment by kkmuffme** [comment]
I tested it & it works with the default WC, I need 1 more week until I can check why it's not working in my custom one (& if there can something be inferred from it for a more general case, as I saw that is what's being worked on)

**Comment by kasparsd** [comment]
@kkmuffme Were you able to confirm the issue with your custom login shortcode?

**Comment by kkmuffme** [comment]
Finally checked it, tested it in default WP from versions 4.5-5 and WooCommerce from 2.5 until 3.5 both with & without 2 factor users and various themes & customised login forms.

The solution that made it work:
add_action( 'wp_login', array( __CLASS__, 'wp_login' ), 10, 2 );

to this:
add_action( 'wp_login', array( __CLASS__, 'wp_login' ), -1, 2 );

Besides the fact that this fixes the bug for me, this essentially makes sure that the 2FA is more secure, since we really want the 2FA verification to be the first thing to be checked on login, so even before some hooked something else to wp_login.
Since a lot of devs don't know that actions can have a negative number, going with -1 is sufficient I think (compare to like -9999)

Another thing:
could the ids "backtoblog" and "loginform" be changed to "back-to-blog" and "login-form"?

Could you contribute/commit this, so I don't have to clone the repo for this small change, thanks a lot!

**Comment by kasparsd** [comment]
Thanks for the testing and suggestions @kkmuffme!

Is WooCommerce using an earlier priority for `wp_login`?

> Since a lot of devs don't know that actions can have a negative number, going with -1 is sufficient I think (compare to like -9999)

Using `-1` sounds like a good solution. It could, however, introduce a breaking change for some users that rely on the current priority `10` (such as [this suggestion](https://github.com/georgestephanis/two-factor/issues/84#issuecomment-230037402) and a few others I've found in the comments).

I'm not sure of the best way to solve this...

**Comment by kkmuffme** [comment]
Regarding the single sign on - I think the better way to do this, is to do an apply_filters in 2FA plugin to "skip" the 2FA for single sign on.
So other devs/plugins can easily disable 2fa for specific users.

```
$require_2fa = apply_filters( 'require_2fa', true );

if ( $require_2fa === true ) {
.... current code
```

**Comment by kasparsd** [comment]
@kkmuffme Did you find plugins that are using an earlier priority for `wp_login`? I'm seeing [priority 10 here](https://github.com/woocommerce/woocommerce/blob/6a89a76c114c9d83097777df6ffa8bfa04fe8a6f/includes/wc-user-functions.php#L751).

**Comment by kkmuffme** [comment]
@kasparsd there are lots of customisations/custom plugins that are hooked in the 1-9 range, to modify default WordPress/Woocommerce behavior or add additional functionality. e.g. for language redirects upon login,... At some point even WooCommerce used priority 1 for wp_login with cart.

The issue is also not really what is there now (as that could be modified) but more the risk of someone circumventing 2FA by using a priority less than 10. Afaik there is no case where we want 2 FA to be easily disabled, by just someone putting a add_action with priority 1. Thus the option with the apply_filters would still allow devs to disable 2FA, but he would need to know what he is doing & does it on purpose by adding the filter.
but add_action wp_login with priority 1-9 can happen easily accidentally and would break 2FA from working, which is a security risk.

**Comment by kasparsd** [comment]
I think we've confirmed that the plugin works correctly with the default WooCommerce login shortcode so I'll close this issue. 

@kkmuffme Could you please open a new issue for adjusting the `wp_login` hook priority to continue that discussion. Thanks!
