### ISSUE TITLE
Where are settings?

### ISSUE THREAD

**Issue by koreos** [georgestephanis/two-factor#268]
Hello, sorry but I'm new on WP. I installed this plugin but can't see settings. How can I use it?

**Comment by kasparsd** [comment]
Exactly what @WM4362 said. Here is a screenshot of the settings:

![plugin-settings](https://user-images.githubusercontent.com/169055/50507792-a6fd6d80-0a87-11e9-9795-b1d59fa8b510.png)

**Comment by koreos** [comment]
Thank you very much! I will use support link when I will find a bug. 
This plugin is amazing and should be in core! Everyone need good security!
