### ISSUE TITLE
allow multiple TOTP tokens

### ISSUE THREAD

**Issue by wrosenauer** [georgestephanis/two-factor#269]
I'm using Yubikey TOTP with the plugin which works totally fine.
But for backup reasons I have a second Yubikey. Technically it should be possible to support multiple tokens but I do not find a way in two-factor to achieve that.
Cold this be made possible?

**Comment by joshbetz** [comment]
I do this by manually adding the the same TOTP token to multiple devices. I haven't come across any services that support multiple TOTP tokens.

**Comment by wrosenauer** [comment]
Thanks for the feedback and checking possibilities.
I tried 2FAS Light before with Wordpress and I was able to use two different Yubikeys with one account.
I'm pretty new in using Yubikeys and followed (amongst others) this article:
https://ocramius.github.io/blog/yubikey-for-ssh-gpg-git-and-local-login/
But you are probably right that this is no typical feature. Just trying to checkout my backdoor options in case hardware gets lost or broken.

**Comment by joshbetz** [comment]
If you have a Yubikey that supports U2F, you can use that instead of TOTP as long as you use a browser that supports it. Chrome has U2F support by default and Firefox supports it with an option. Multiple hardware tokens _are_ supported via U2F.
