### ISSUE TITLE
Missing markup before login_footer action

### ISSUE THREAD

**Issue by claytoncollie** [georgestephanis/two-factor#274]
https://github.com/georgestephanis/two-factor/blob/dac65f43845cb9d0367d0771e7b0503363ab422d/class.two-factor-core.php#L501

Hi there, thanks for this building this plugin. It's very easy to use.

I've added a bit of markup and styling to my login page and I've run into an issue. It looks like there needs to be a closing <div> tag added just before the login_footer action on line 501. Without that tag, the markup from login_footer is mixed into the #login div creating styling issues.

If you compare the standard wp-login.php file on a stadnard install, there is a closing <div> tag on line 271 that comes directly after the Back to Blog and Privacy policy links.

Thank you!

**Comment by kasparsd** [comment]
Thanks for opening the issue @claytoncollie!

I'm looking at the [WP source code](https://github.com/WordPress/WordPress/blob/6b6201ed8937f56ff2d2e65c387db834e76b78f5/wp-login.php#L274-L292) and can't find the tag you are referencing:

```php
	<?php
	/**
	 * Fires in the login page footer.
	 *
	 * @since 3.1.0
	 */
	do_action( 'login_footer' );
	?>
	<div class="clear"></div>
	</body>
	</html>
	<?php
```


Line 501 seems to match exactly what is in WP core.

https://github.com/georgestephanis/two-factor/blob/dac65f43845cb9d0367d0771e7b0503363ab422d/class.two-factor-core.php#L499-L501

Note that the closing `?>` tag is at the end of the line instead of a new line. It shouldn't matter, though.

Let me know if I missed anything. Thanks!

**Comment by kasparsd** [comment]
@claytoncollie Are you referring to [this closing `</div>` element](https://github.com/WordPress/WordPress/blob/6b6201ed8937f56ff2d2e65c387db834e76b78f5/wp-login.php#L272)?

**Comment by claytoncollie** [comment]
Yes. That's the one I belive is missing.

*Clayton Collie*
clayton.collie@gmail.com
214-577-6712

**Comment by claytoncollie** [comment]
That's the one I believe is missing.

I think a closing div should be on line 477 two-factor-core class.

**Comment by claytoncollie** [comment]
login_header and login_footer should not be placing markup inside the #login <div>

**Comment by claytoncollie** [comment]
I can confirm that adding a closing </div> works properly on my end.

**Comment by kasparsd** [comment]
Thanks @claytoncollie! Would you like to open a pull request with the suggested change? I'm not sure if I'll get to it before the end of the week.

**Comment by claytoncollie** [comment]
@kasparsd I can certainly try! This is my first ever PR so bear with me. I cloned the repo to my local, checked out a new branch `fix/add-closing-markup` and made the change. After committing on loca, I am trying to push up to the origin and access is deined. Do you need to make that branch first or give me some sort of access to send up a branch ready for review?

**Comment by kasparsd** [comment]
@claytoncollie Thanks for doing that -- you got everything right!

Re: permissions -- I don't own the repo so I can't change user permissions. Could you please [fork the repo to your own GitHub account](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork), create the same branch and then push it to your repository and finally open a pull request to this parent repository?

**Comment by claytoncollie** [comment]
@kasparsd yes sir!
