### ISSUE TITLE
FIDO not working with Yubikey 5

### ISSUE THREAD

**Issue by LetzPlay** [georgestephanis/two-factor#275]
Hey,

I am using the PlugIn now for a few years with the TOTP-Option. Now I got a Yubikey 5, registering it worked (console error: setting getter-only property "u2f"), but if I want to login it shows the page but my Key doesn't light up, pressing the key doesn't do anything. 

I am Using WordPress 5.1.1 and https, also tried to delete the key and set it up a few times. Tried Chrome, Edge and Firefox.

**Comment by kasparsd** [comment]
Thanks for reporting the issue!

Which browser did you use for registering the device? Could you please paste the full error message you got when registering the device? 

I suspect it didn't actually register the device due to that error.

**Comment by LetzPlay** [comment]
Registered it with Firefox 66.0.2 and got this error:
```
TypeError: setting getter-only property "u2f"[Weitere Informationen] u2f-api.js:17:5
    <anonym> https://[mydomain]/wp-content/plugins/two-factor/includes/Google/u2f-api.js?ver=0.1.0-dev.2:17
```
Registered it with Chrome 73.0.3683.103 => no error => also not working

**Comment by kasparsd** [comment]
Sounds really similar to #211. 

Did you enable the [U2F feature](https://www.yubico.com/2017/11/how-to-navigate-fido-u2f-in-firefox-quantum/) flag?

**Comment by LetzPlay** [comment]
Yeah I enabled it

**Comment by kasparsd** [comment]
Here is a video showing key registration on Firefox 67 with the [U2F feature flag](https://www.yubico.com/2017/11/how-to-navigate-fido-u2f-in-firefox-quantum/) enabled:

![firefox-u2f-register](https://user-images.githubusercontent.com/169055/56490004-5acdb180-64ec-11e9-84b6-f55d954c945e.gif)

I've opened #283 to address the JS warning in the browser console but that isn't impacting the registration and sign processes.
