### ISSUE TITLE
Add l10n support?

### ISSUE THREAD

**Issue by Sonic853** [georgestephanis/two-factor#280]
Great plugin. I can add it, as well as Simplified Chinese.

**Comment by kasparsd** [comment]
Thank you for opening the issue and the pull request.

The translations can be added and updated [here on WordPress.org](https://translate.wordpress.org/projects/wp-plugins/two-factor/). Some of the strings are missing the `two-factor` textdomain because they're synced with WordPress core functions.

**Comment by Sonic853** [comment]
Thanks Reply!
I have submitted translations to ["Chinese(China)" on WordPress.org](https://translate.wordpress.org/projects/wp-plugins/two-factor/dev/zh-cn/default/).

**Comment by kasparsd** [comment]
Thanks @Sonic853! 

Could you please update #281 to only include updates to `class.two-factor-core.php` string textdomain? We could then merge those in and they would become available on WP.org for translation.

**Comment by Sonic853** [comment]
Updated.

https://github.com/georgestephanis/two-factor/pull/281/files#diff-fa3c61990ea53ab19ab294efedcfeffaR61

I read the [WordPress Developer Resources](https://developer.wordpress.org/reference/functions/load_plugin_textdomain/), but if use "load_plugin_textdomain( 'two-factor' );", he does not seem to load the translation file on the root of the plugin directory.

![20190416174702](https://user-images.githubusercontent.com/8389962/56199691-fafc8400-606f-11e9-813a-9c16a4668c34.png)

![20190416173337](https://user-images.githubusercontent.com/8389962/56199595-cb4d7c00-606f-11e9-80dc-a4b48228152d.png)
That's loaded.

![20190416175040](https://user-images.githubusercontent.com/8389962/56199800-3008d680-6070-11e9-8f61-bf4cb5acdf1d.png)
But that's not loaded.

**Comment by kasparsd** [comment]
@Sonic853 WordPress will load the translation files from the [`WP_LANG_DIR` directory here](https://github.com/WordPress/WordPress/blob/24e2829eb95e2fdb31c5774b510d0b39cee13034/wp-includes/l10n.php#L790).

**Comment by Sonic853** [comment]
Updated.
