### ISSUE TITLE
Login button is disabled

### ISSUE THREAD

**Issue by ricky-dodo77** [georgestephanis/two-factor#293]
Hi, I noticed the OTP can only be submitted using return key and not the login button, that looks permantently disabled at all times, I've opened a support thread on Wordpress too:

https://wordpress.org/support/topic/otp-button-is-disabled/

**Comment by kasparsd** [comment]
Thanks for reporting the issue @ricky-dodo77! Can you please share a screenshot of this? Thanks!

**Comment by kasparsd** [comment]
Here is how it looks during login for me:

![otp-login-screen](https://user-images.githubusercontent.com/169055/57297501-6d450f00-70d8-11e9-868f-f5ed7c8439e6.png)

**Comment by ricky-dodo77** [comment]
I tested it on a clean WP installation, it seems there is a conflic with https://it.wordpress.org/plugins/admin-custom-login/ so it is more likely on their end?

**Comment by kasparsd** [comment]
@ricky-dodo77 I won't be able to comment on that since I haven't used that plugin. Could you please try replicating the issue without the Admin Custom Login plugin?

**Comment by ricky-dodo77** [comment]
on a fresh clean WP site it is not replicating. The custom login probably disable the submit button accordingly to its criteria, probably is expecting user/pasword to be entered, it is hard to tell but since two-factor works on clean installation if it probably on their end; ive opened a thread https://wordpress.org/support/topic/conflict-with-two-factor-plug-in/

**Comment by kasparsd** [comment]
Thanks for the confirmation @ricky-dodo77!

I'll close this for now until we know if there is anything that needs to be changed on the two-factor plugin side, OK?
