### ISSUE TITLE
Filter to disable auth methods

### ISSUE THREAD

**Issue by menathor** [georgestephanis/two-factor#299]
Hi guys,

Are there any filters to disable specific auth methods? If not, would it be possible to add them? I'd like to just use Google authenticator. It would add a lot of flexibility if administrators could have some control over this.

Cheers!

**Comment by menathor** [comment]
Ah my bad, just saw this was already requested in https://github.com/georgestephanis/two-factor/issues/247. Closing this issue

**Comment by kasparsd** [comment]
@menathor See the filter here:

https://github.com/georgestephanis/two-factor/blob/ab8d6510a17606b200d1e44a603c13b5014bac52/class.two-factor-core.php#L80-L89

**Comment by menathor** [comment]
@kasparsd Thanks, just what I needed!
