### ISSUE TITLE
Add Javascript AJAX-y goodness to Application Passwords.

### ISSUE THREAD

**Issue by georgestephanis** [georgestephanis/two-factor#3]
Users should be able to generate application passwords and delete existing application passwords without a page refresh -- just do it through admin-ajax.php

**Comment by voldemortensen** [comment]
I'm working on this currently.

**Comment by georgestephanis** [comment]
cc: @JeffMatson who also seemed interested in this.

**Comment by JeffMatson** [comment]
@voldemortensen Any luck on this?

**Comment by aaroncampbell** [comment]
Has anyone done any work on this yet? TOTP could use some JS love too, and it would be nice to be able to reuse as much as possible, etc

**Comment by shield-9** [comment]
Related #103

**Comment by georgestephanis** [comment]
Closing in favor of d8a85bb removing Application Passwords from this repository and running it in its own instead.
