### ISSUE TITLE
No FIDO2 Prompt popup on Android

### ISSUE THREAD

**Issue by mars-online** [georgestephanis/two-factor#301]
I cannot tell for sure where the issue is located, but on Android I do not get a popup from the browser to authenticate the hardware token in Chrome or Firefox.

To be sure the browsers are compatible I double checked with webauthn.io and github - my setup works on these pages without any issue.

**Comment by kasparsd** [comment]
The plugin still uses the first version of FIDO U2F. There is an open ticket to add WebAuthn support #232. Could that be the cause of the problem?

**Comment by mars-online** [comment]
This sounds reasonable and I was not aware of missing webauthn support.
