### ISSUE TITLE
Unable to login to my site. Getting `Invalid verification code`.

### ISSUE THREAD

**Issue by neoswf** [georgestephanis/two-factor#305]
I'm unable to login to my site. Using the same codes I always had. 
I do not get 403. Only 200, but with querystring - `?action=validate_2fa` and on screen error `ERROR: Invalid verification code`. 
Is there anything I can do? One option i'm thinking of is to delete the plugin's folder, but do you guys think it might solve the problem for the long run? One thing I am afraid of is that someone hacked into my site & caused this. 

What do you think? 
Thank you.

**Comment by kasparsd** [comment]
@neoswf Thanks for reporting the issue!

Which authentication method are you using -- email or one-time passwords?

This is usually caused by the clock differences on your server when using one-time passwords with Google Authenticator, for example.

**Comment by neoswf** [comment]
Hey @kasparsd and thank you so much for returning so fast to me!
I'm using two steps authentication, using token. What can I do now, to be able to access my website admin?

**Comment by neoswf** [comment]
Can I delete the plugin folder without it will damage the site in someway? and then reinstall the plugin, in order to solve my problem? Thank you.

**Comment by neoswf** [comment]
Fixed. Have renamed the plugin folder, logged-in, and installed again the plugin.
