### ISSUE TITLE
We Need A Logo.

### ISSUE THREAD

**Issue by georgestephanis** [georgestephanis/two-factor#47]
We need a logo and assets for the plugins banner.

Break out your Papyrus and Comic Sans, warm up the Rainbow Gradients and Drop Shadows, it's time.

**Comment by aaroncampbell** [comment]
Is there any reason not to use the [dashicons SVG lock](https://github.com/melchoyce/dashicons/blob/master/svg/lock.svg) for the logo?

**Comment by georgestephanis** [comment]
wfm.  I just wasn't sure if we wanted a banner as well and other such assets.  Happy to add anyone to the .org repo for configuring.

**Comment by RodSalm** [comment]
I'd be glad to submit an idea I have for this. What parameters do Ineed to consider? Presuming square dimensions. Anything else?

**Comment by aaroncampbell** [comment]
I had an idea...but my design skills are sorely lacking. I made it as an SVG because I like how well those scale and also because it's more like programming. Basically, it's a skeleton key on the left with a WordPress logo for the head (handle) and the letters WP for the bit. Then there's a plus sign in the middle and a 6 digit code (42 42 42) down the right

![two-factor-logo](https://cloud.githubusercontent.com/assets/802412/9702035/d9dbec5c-5411-11e5-96e1-ac3779c1c090.png)

For some reason, the middle line of the W in the bit of the key, and the vertical lines of the 4s are off a little. They're different with Chrome and Firefox. I'm sure I can figure it out, but we may also need someone to pretty things up anyway.

The actual hand coded SVG: https://gist.github.com/aaroncampbell/cd729e5355ba01686968

**Comment by aaroncampbell** [comment]
It looks right in both Chrome and FF now: https://gist.github.com/aaroncampbell/cd729e5355ba01686968
![two-factor-logo](https://cloud.githubusercontent.com/assets/802412/9702217/d2039626-5419-11e5-87ff-d244db4a13fb.png)

So there it is, I threw my hat in the ring.

**Comment by stevenkword** [comment]
I like just the key (without the 42s), personally.  Clever what you did with the grooves, Aaron. ;)

**Comment by aaroncampbell** [comment]
I thought having the key **and** the code made it **two**-factor

**Comment by georgestephanis** [comment]
I'm fine with either, I'm just not sure how that would display at smaller sizes.

**Comment by valendesigns** [comment]
@georgestephanis What size is the logo meant to be displayed at?

**Comment by georgestephanis** [comment]
128px square.

https://make.wordpress.org/plugins/2014/08/21/plugin-icons/

Still looks decent when resized to that.  I'm fine shipping this if y'all are happy.

**Comment by valendesigns** [comment]
Why 424242 though, what is the significance of that number combination or is there none?

**Comment by georgestephanis** [comment]
42 is clearly the answer to life, the universe, and everything.

**Comment by aaroncampbell** [comment]
@georgestephanis has it.

My thought process went like this:
I want a 6 digit code. 123456? No, boring. 501337? No, L33T SP34K isn't me.  I should work in 42...that's the answer to everything. 424242 it is.

**Comment by stevenkword** [comment]
@valendesigns its a reference from Hitchhiker's Guide to the Galaxy. 
https://en.wikipedia.org/wiki/Phrases_from_The_Hitchhiker%27s_Guide_to_the_Galaxy#Answer_to_the_Ultimate_Question_of_Life.2C_the_Universe.2C_and_Everything_.2842.29

**Comment by valendesigns** [comment]
@stevegrunwell Yeah lol, I remembered the reference right after George responded.

@aaroncampbell Could we add a bit more symmetry in the heights of the two elements? The key looks a decent amount larger. We could either bump up the 424242 or scale down the key. The plus sign size is a bit off, as well. It all just feels weighted more to the left throwing off the rhythm. We probably could create this as an AI file instead of as an SVG for a much easier editing experience. Not to discount the fact you hand coded an SVG, well done. :smile:

**Comment by aaroncampbell** [comment]
tl;dr: Here's take 2, but consider this public domain. Do with it as you please. Design is NOT my strong suit.

I shrank the key vertically to make it the same height as the 424242 code (21 lower with the top, 23 higher with the bottom, taking all the hight out of the shaft). I also moved it right 10 to try to account for the weight you're talking about (this is one of the designer "feels right" things though, so kind of outside my purview). The plus is mathematically centered, so I'm not sure how it's "off".

[The diff](https://gist.github.com/aaroncampbell/cd729e5355ba01686968/revisions#diff-b73b6285a207aaef0f177420ac006dcf)

The new image:
![two-factor-logo](https://cloud.githubusercontent.com/assets/802412/9767481/0d6b80d0-56e4-11e5-9477-21e0d8bd7eb2.png)

You can do whatever you want with it. All the symmetry/weight talk is where you lose this programmer. If you give me parameters (like "the key should be 14 units shorter"), I'm happy to comply and keep it hand coded if you want. If you want to make an AI out of it, that's fine too. Those kind of programs delve far outside my comfort zone.

**Comment by valendesigns** [comment]
The heights look perfect now, thank you. The only thing I would change is to move the key left or the plus sign right to balance the two elements and then it's golden in my book. I'm not sure of the amount other than to say maybe 15px based on what I'm looking at above.

**Comment by aaroncampbell** [comment]
Key Shifted -5
![two-factor-logo-keyshift-5](https://cloud.githubusercontent.com/assets/802412/9769041/2383bcb2-56ed-11e5-8c65-50db06fa37db.png)

Key Shifted -10
![two-factor-logo-keyshift-10](https://cloud.githubusercontent.com/assets/802412/9769039/237d9e54-56ed-11e5-8fd2-aaa4840541d3.png)

Key Shifted -15
![two-factor-logo-keyshift-15](https://cloud.githubusercontent.com/assets/802412/9769040/2380e622-56ed-11e5-84ba-400a0ee9b7fc.png)

I wish they put a border around the image or a background or something here so you could better tell where the image ends

**Comment by valendesigns** [comment]
I vote -15, it looks really balanced to me. We could use a solid background color instead of just transparent.

**Comment by aaroncampbell** [comment]
https://gist.github.com/aaroncampbell/cd729e5355ba01686968 is updated with the -15. I like the transparent bg personally. I was just saying on this git comments thread, since they don't center images, it was hard for me to tell how it looked without highlighting it or opening it some other way.

**Comment by valendesigns** [comment]
I see what you mean. Now that I can see the alignment with the container visible I'm not sure about going the full -15. We could just move everything to the right to center all elements and not worry that the plus sign is dead center. Thoughts?

**Comment by aaroncampbell** [comment]
This shifts everything 19 units right to center it all
https://gist.github.com/aaroncampbell/cd729e5355ba01686968

**Comment by valendesigns** [comment]
Removed 9 of those units https://gist.github.com/valendesigns/59e573139ee69cf543f1

**Comment by aaroncampbell** [comment]
Works for me. I updated my gist too, mostly because I wanted to fix a comment that said "hoes to" instead of "goes to".
https://gist.github.com/aaroncampbell/cd729e5355ba01686968

**Comment by dustinleer** [comment]
Throwing my hat into the ring here, just some thoughts.

![two-factor](https://cloud.githubusercontent.com/assets/1885540/9798345/5a4f6174-57ce-11e5-87bf-1d2903c9601f.png)

**Comment by jashsayani** [comment]
@dustinleer I like the Wordpress logo with the lock. Simple and clear.
