### ISSUE TITLE
Backup Codes: Add print option

### ISSUE THREAD

**Issue by kraftbj** [georgestephanis/two-factor#54]
Most backup code providers will offer a print link that opens up a generic window suitable for printing codes.

**Comment by stevenkword** [comment]
Absolutely.  I think this will need to wait on some UX decisions from the core team, but we should definitely do this.

**Comment by georgestephanis** [comment]
It should be trivial to create a popup window with javascript that just contains a 'print' button and the ten new codes -- perhaps with some additional line like `Two-Factor Backup Codes for %username% at %sitename% <%siteurl%>` or the like.

**Comment by valendesigns** [comment]
When with a save button instead in #82.
