### ISSUE TITLE
User Profile: Ensure all feature settings are grouped together.

### ISSUE THREAD

**Issue by kraftbj** [georgestephanis/two-factor#55]
All of the settings appears to be hooked onto `show_user_profile` directly without priority. This can lead to an odd ordering on a profile with other plugins adding in features. Example with Yoast SEO installed:

https://cloudup.com/cNq7kO2kKcW

I'm happy to do a PR for this based on whatever approach is deemed best. My initial thought is have a intermediate function that all settings hook into, e.g.

```
function prefix_user_settings_display() {
do_action( 'show_user_security_settings' );
}
```

Then within each function that adds to the profile, swap out the `add_action( 'edit_user_profile',        array( __CLASS__, 'show_user_profile' ) );` with
`add_action( 'show_user_security_settings',        array( __CLASS__, 'show_user_profile' ) );`

Thoughts?

**Comment by shield-9** [comment]
How about adding `do_action( 'show_user_security_settings' );` in `Two_Factor_Core::user_two_factor_options()`?

**Comment by kraftbj** [comment]
I'm not as familiar as I should be with the code base :). Sounds solid.

I can PR that today/tomorrow for the core itself and the methods currently in place.
