### ISSUE TITLE
Add some sort of fallback for alternate login forms.

### ISSUE THREAD

**Issue by georgestephanis** [georgestephanis/two-factor#61]
Some login forms -- [WooCommerce, for example](https://github.com/woothemes/woocommerce/blob/8b601adb3ca9d3e20da7b94c2e8d7dd93e4bf4fe/includes/class-wc-form-handler.php#L754-L823) -- use alternate login forms and don't submit to `wp-login.php` -- and so we don't have the normal wp-login.php functions like `login_header()` available.

I'd suggest we add in a check and if we're trying to authenticate without being on wp-login, we stash the redirect param and redirect to wp-login to handle the 2fa part, then redirect back to continue.

**Comment by kraftbj** [comment]
Could we use the `authenticate` filter (or one of the related cousins)?

**Comment by georgestephanis** [comment]
> Could we use the authenticate filter (or one of the related cousins)?

That's a different issue.  This one is the case of having the markup available to us that we need for presenting the second step.

By using `wp_login` instead of `authenticate` we give other plugins the chance to decide whether or not the traditional user/pass is accepted.  I'd hate to short circuit that.
