### ISSUE TITLE
iPhones don't like certain secrets

### ISSUE THREAD

**Issue by aaroncampbell** [georgestephanis/two-factor#72]
The issue comes when you try to scan the QRCode with Authy or Authenticator on an iPhone. All the codes listed here scanned fine in Authy and Authenticator on Android. I don't have any iThings, but after enlisting some additional help (thanks Gerroald and Chris), here is what we have found:

I can't find a pattern. Here is a sample of tested secrets:
```
Works - 16
PCUAODJGC4
K5PKQLJXZE
ZFNI6CAJKY
AYXU3SFQUU
BKYW2YQFSI
VM6CKYH464
33OLV36CJE
L5LSRNRFP4
FDMKI76Z4I
XQN3RMLPJE
TDKB5C5PLM
BQLOVNSKXA
UGBGNXA4UM
GWYFA2PQTQ
JWIJS33WLY
OVG2YI472U

Doesn't Work - 34
MFHXO37YL7
D4ACQ2IEUP
CUYFNOXVQX
IWJCJDXQMN
56B67WMEMH
BXUBDQEJGD
5SQLGCU54C
4WCUJQF2GG
UGXEA3E5IP
74MP3SBVZR
AMDPNKC3GJ
UTO3CUD2UF
C5SEHK4MOH
YXJOI4F5NS
R54HXEKST5
UNVZ5NXHDL
AJAX3VKTET
3PE5CSCUXT
IY6MBR6XY2
3DCHEYW7ZW
EUPTLSCXMF
UBUZL6NAQB
UUJVMWC3OS
NSMYA4FBDX
DADVCUB65B
SIZBQM7VGZ
QB5I5ZYPHL
KX63TJE3RN
2XJZVWDSQ7
QSBJN4GTVZ
72FGY7TFIX
SIE3SSJBFF
OJL45N4G47
6RLC2YCT3S
```
These are all based on the 80bit secrets (10 digits) that we've been using. The spec actually says the secret should be at least 128bit (16 digits) but recommends 160bit (20 digits). So we tried 160bit:
```
Works - 4
LJSW6GLMYSXYMZ5P5BLQ
PVGGUSRCTJTJETY2KREQ
SPTLBWOLXY7P6W6I5SDA
WCCEPMA5JJBMNLQKJHAA

Doesn't Work - 24
UPMQN2TCMGYJVSLTMQ6V
Y53HYVZVMSN3UPRI54HH
UMOPXCHQV5HVGMD4XQQB
FGUAPWMRKAEXIVEPNNTL
6WXJUIM5Q3RDIG6TOKBC
7S2ICHPD5NEE3G6DDLNE
GB3FHZMOV4ALBE4ECD6W
X2TMQQKNUGKO4QG7BB6V
LZJFQO64EP4XY5TZ255R
HLI4RF43EPE3UWOBGH35
WRNLEK3K6AKQP2GUC56B
LLA4CQE5VCNNMCYEU3HD
I2FQDCDFU4A6HZPGYUG5
WTWAPV4W6VF37HYLJDEP
XFZ3DDYQDMWWSWSY5VWR
HJZFPTSRE554463WF2OR
UJ3YAREU3DT3RY6LVPXT
7FINEBDPUIGF7YYJED3H
KM5POSRVVIGYUJEO2LB4
BBNRK4XQRVN3UFXVWLOL
447A7RWFK73MNICGWXON
I4EPZZ7ZNQ7HV5NUBXTE
XJ7KQEOMFSC7DVAZ5NV7
BE7QZSLWQWMFAXJVFOVW
```

Then we tried 128bit secrets, and they all worked.

The problem is that it seems like 128bit secrets fixes the issue, but I don't know why. I hate implementing a "fix" and not knowing exactly what the problem is that it's fixing or why it fixes it.

Anyone with more iOS knowledge that could weigh in on this would be much appreciated.

**Comment by aaroncampbell** [comment]
There's an update on this. @chrisbliss18 and @gerroald both put significant time into this for iThemes Security Pro. When we get everything working there I'll try to port the fixes back here, but the basics are:
The secret is currently being generated as a random string of characters that are all base32 safe. However, it needs to actually be generated as a random string of characters that are then base32 encoded. We're looking at the best ways to generate the original string to encode and also testing to make sure our encoding is rock solid.

**Comment by kasparsd** [comment]
Here is a PHP library (MIT license) that implements a Base32 Encoder/Decoder according to RFC 4648 https://github.com/ChristianRiesen/base32

**Comment by aaroncampbell** [comment]
We have a functional fix for this, I just need to get a few hours to try to port it back from iThemes Security to here. It's definitely a much more complete fix than the on in #90 (which will NOT fix the issue for many phones still) so I recommend closing that one.

**Comment by kasparsd** [comment]
> We have a functional fix for this

Glad to hear that @aaroncampbell!

I still think that following the [RFC4226](https://tools.ietf.org/html/rfc4226#section-4) would be a good idea, though:

> R6 - The algorithm MUST use a strong shared secret.  The length of
   the shared secret MUST be at least 128 bits.  This document
   RECOMMENDs a shared secret length of 160 bits.

**Comment by kasparsd** [comment]
@aaroncampbell I have ported the `base32_encode` from iThemes Security in #93.
