### ISSUE TITLE
FIDO U2F can be bypassed simply by using an unsupported browser

### ISSUE THREAD

**Issue by valendesigns** [georgestephanis/two-factor#78]
We need to close this security hole by forcing an admin lockout if attempting to login with an unsupported browser and FIDO U2F is the primary provider.

**Comment by shield-9** [comment]
Similar issue will happen with TOTP if TOTP setting is not finished.

So I think it is better to force email provider to always be enabled if any other methods is enabled.

**Comment by valendesigns** [comment]
Sounds sane to me. Closes the hole in security due to an insufficient browser and doesn't completely lock you out. +1

**Comment by ragnarkarlsson** [comment]
Is it worth considering a column in the user admin which is "secondary" radio button as per "primary" where user can check which backup method they want to fall back to. Then the radio buttons can be disabled if the user has not enabled that method and if no backup method has been selected default to email?

**Comment by dbrgn** [comment]
In addition, can you show a message to the user that the primary method was skipped due to [REASON], e.g. "because your browser does not support the U2F authentication method"?

**Comment by joshbetz** [comment]
I think we should face a secondary method for U2F, but fix the bug where TOTP reports as enabled even if it hasn't been fully set up.

**Comment by kasparsd** [comment]
This should be fixed in #162.

**Comment by kasparsd** [comment]
Fixed in #162.
