### ISSUE TITLE
Unable to remove TOTP

### ISSUE THREAD

**Issue by ragnarkarlsson** [georgestephanis/two-factor#86]
I added TOTP with my Yubikey slot 2 and the Yubico Authenticator successfully, but then realised I would likely need to use this on my chromebook and/or want to use slot 2 for my keepass database which requires OATH-HOTP method.

There is no option to delete config settings for a OTP once it is added to revert to a different Google Authenticator.

**Comment by iYianni** [comment]
I am having the same issue.

One of our users has lost their phone and there is no way to remove/change the OTP settings from their WP user account. Is their a workaround for this? I am using version 0.1-dev-20151111.

**Comment by wimercer** [comment]
I have a dev site for my organisation to try this out on and I also can't reset the OTP. Once the OTP is set, it's set for good without anyway of reseting it.

**Comment by kasparsd** [comment]
The OTP secret is stored in user meta `_two_factor_totp_key` field and the QR code is not displayed if the field is populated.

I just checked that Google only allows resetting the secret key:

> Once you complete this setup, the codes generated by your old Authenticator app will stop working.

which is probably what we should also implement.

**Comment by ledurnan** [comment]
Same issue.

**Comment by dartiss** [comment]
Again, same here. I'm wishing to switch over to a different authenticator, hence needing to do this.  

@kasparsd - where is this stored?

**Comment by ragnarkarlsson** [comment]
@dartiss it is the user's profile meta field `_two_factor_totp_key` in the database, from memory if you delete that it will reset that option allowing you to restart adding an authenticator. I've used User Profile Meta Manager plugin to easily do so as an admin to date.

**Comment by dartiss** [comment]
Thanks @ragnarkarlsson. Yes, I managed to find it in the meantime. The following will remove it...

`DELETE FROM `wp_usermeta` WHERE `meta_key` = "_two_factor_totp_key"`
