### ISSUE TITLE
XMLRPC bypasses 2fa

### ISSUE THREAD

**Issue by aaroncampbell** [georgestephanis/two-factor#87]
It looks like XMLRPC uses `authenticate()` directly. The app password system works great with this, as it hooks into the `authenticate` filter. However, the rest of the plugin that ​_enforces_​ 2fa hooks into `wp_login` which fires in `wp_signon()` but NOT in `authenicate()`. Basically, you can sign in via XMLRPC with a user/pass OR a user/appPass. Both work and neither needs 2fa

**Comment by kraftbj** [comment]
For XMLRPC, I would expect the user/pass should fail. The user/app should work without 2fa (since XMLRPC clients don't have a real way to handle 2fa).

**Comment by aaroncampbell** [comment]
Yes, that's definitely the expected behavior. App passes are meant to be 2fa work arounds, that work ONLY with XMLRPC (or another API). Regular passwords are supposed to be secured by 2fa though and should not work at all without it, and since XMLRPC doesn't really offer any way to prompt for a 2fa token, we should just make them not work for APIs

So, what do you guys think is a good approach here? Any thoughts?

We have a couple options that I see:
1) We let the Application Passwords module handle this. It already loops through the list of hashed application passwords, testing each. If one doesn't match, we could return null (invalid authentication) rather than the user that was already being passed in. We would need to move the filter to hook in a little later to make sure we're always checking AFTER the default authentication happens. We would also want to add an `if ( Two_Factor_Core::is_user_using_two_factor() )` check to make sure we're not refusing the login for someone that isn't using 2fa.

The advantages: The code to decide if we're using an API is already there. It's a simple change.
The disadvantage: It feels weird that the Application Password module is what enforces 2fa for API calls. Currently it's so decoupled that you could pretty much just remove it and everything would still work.

2) We could hook into `authenticate` late from within the core 2fa module. We'd do pretty much what is mentioned in #1, duplicating the code that decides if we're using an API, and instead of checking against application passwords, we would check to see if the password matches the one in the user table. Basically return null `if ( Two_Factor_Core::is_user_using_two_factor() && $password === $regular_userpassword )`. It's a little bit of code duplication, but not much.

**Comment by aaroncampbell** [comment]
I'm leaning toward option 2

**Comment by aaroncampbell** [comment]
The more I play with the code, the more I lean toward number 1. The main reason is that there are so many ways that other authentication systems can hook in, that it's hard to tell if the user authenticated with a valid app password unless we:
A) Actually loop through them and check...this not only makes sense to do in the app password module, but is ALREADY happening there.
B) Set some sort of flag when a valid app pass is used.

B feels a little hacky, and A makes for a clean solution except that it means we tie in much tighter to App Passwords.

**Comment by aaroncampbell** [comment]
This is fixed in the [xmlrpc-bypass branch](/georgestephanis/two-factor/tree/fix/xmlrpc-bypass) using method 1A.

**Comment by georgestephanis** [comment]
Closing in favor of d8a85bb removing Application Passwords from this repository and running it in its own instead.

**Comment by kasparsd** [comment]
Re-opening this since we should not let users with 2FA enabled login through REST or XML-RPC without entering the actual second factor. Maybe suggest using the Application Passwords plugin in the error message.
