### ISSUE TITLE
Does not detect any FIDO keys

### ISSUE THREAD

**Issue by ReagentX** [georgestephanis/two-factor#89]
The plugin from the Wordpress database (vesion 0.1-dev-20151020) does not detect any FIDO keys. Clicking the button just instantly displays "Failed..."

**Comment by valendesigns** [comment]
Are you using Chrome and SSL?

**Comment by ReagentX** [comment]
Yes. 



—
Chris Sardegna
Reagent X Laboratories
reagentx.net

**Comment by kasparsd** [comment]
@ReagentX Could you please post a screenshot of the error? Please include the output of the [developer console](https://developer.chrome.com/devtools) to see if there are any errors.

**Comment by shield-9** [comment]
Close this issue since no response from @ReagentX.
