### ISSUE TITLE
SMS over email?

### ISSUE THREAD

**Issue by JeffMatson** [georgestephanis/two-factor#9]
I feel like we could do SMS via email here.  Rather simple, doesn't require a gateway, and I already have most carrier data from writing WP SMS.  Thoughts?

**Comment by georgestephanis** [comment]
I'd love to see it.

**Comment by shield-9** [comment]
I've made [SMS provider extension](https://github.com/shield-9/two-factor-sms). This is using Twilio API.

**Comment by georgestephanis** [comment]
Nice!
