### ISSUE TITLE
avoid warnings

### ISSUE THREAD

**Issue by voldemortensen** [georgestephanis/two-factor#97]
PHP Notice:  Undefined index: HTTP_HOST in /vagrant/www/wordpress-develop/src/wp-content/plugins/two-factor/providers/class.two-factor-fido-u2f.php on line 54
Notice: Undefined index: HTTP_HOST in /vagrant/www/wordpress-develop/src/wp-content/plugins/two-factor/providers/class.two-factor-fido-u2f.php on line 54

I get these every time I use wp-cli while two-factor is enabled.

**Comment by shield-9** [comment]
Fixed in #98
